### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by sxhsunday** [IDKiro/CBDNet-tensorflow#10]
hi，the batchsize=1,but  when I run train_syn.py, it still out of memory after training for more than a thousand times.

**Comment by IDKiro** [comment]
In README, I said
'In order to reduce the time to read the images, it will save all the images in memory which requires large memory.'
So the OOM is not GPU's memory, you can modify the load code to fix it.

**Comment by sxhsunday** [comment]
OK,thanks
