### ISSUE TITLE
数据集下载问题

### ISSUE THREAD

**Issue by CYL0089** [IDKiro/CBDNet-tensorflow#4]
您好，CBDNet-tensorflow的model和dataset能否以其他方式上传，实在是打不开下载链接（登录微软账号之后显示“不成功很抱歉，在 zjueducn-my.sharepoint.com 目录中找不到cyl964156631@hotmail.com(我的微软账户)”），万分感谢~~

**Comment by IDKiro** [comment]
我建议你再尝试下。
我空闲时会上传到其他网盘（大概是baidu和mega），几天内吧。

**Comment by CYL0089** [comment]
好的，非常感谢，我再尝试一下


 
---原始邮件---
发件人: "IDKiro"<notifications@github.com>
发送时间: 2019年6月3日 00:11:21
收件人: "IDKiro/CBDNet-tensorflow"<CBDNet-tensorflow@noreply.github.com>;
抄送: "CYL0089"<964156631@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [IDKiro/CBDNet-tensorflow] 数据集下载问题 (#4)



我建议你再尝试下。
 我空闲时会上传到其他网盘（大概是baidu和mega），几天内吧。

**Comment by xiaozhi2015** [comment]
Have you upload the dataset.zip to other platform yet? @IDKiro 
I failed to download through your "dataset.zip" link all the time.

**Comment by IDKiro** [comment]
> Have you upload the dataset.zip to other platform yet? @IDKiro
> I failed to download through your "dataset.zip" link all the time.

i'm sorry that i delete the extra link since the model has little changed and forget to re-add it. now you can see the other download link.

**Comment by xiaozhi2015** [comment]
Much thx for your quick reply. ^_^ @IDKiro
