### ISSUE TITLE
batchsize

### ISSUE THREAD

**Issue by haoyuee** [IDKiro/CBDNet-tensorflow#5]
我训练的时候遇到了memory error问题，想请问您在哪里设置了batchsize吗？

**Comment by IDKiro** [comment]
batch_size 是1，如果显存不够是因为patch_size太大，找一下ps=512这一项，内存不够是因为会把所有图片读进内存，节约二次读取的时间。

我添加一个参数吧，方便适应不同的硬件，今天内完成。

**Comment by IDKiro** [comment]
看你的描述，你的memory error指的是显存不够，那你修改 PS = 512 便可以，这是patch_size的大小（指裁剪的输入图像的大小），batch_size是1。

**Comment by haoyuee** [comment]
好的，谢谢，我接下来试一试

**Comment by haoyuee** [comment]
您好，我在调整了PS参数之后依然存在 memory error 的问题，请问可以设置参数让图片分批读入内存训练吗？




------------------ 原始邮件 ------------------
发件人: "IDKiro"<notifications@github.com>; 
发送时间: 2019年7月10日(星期三) 中午12:23
收件人: "IDKiro/CBDNet-tensorflow"<CBDNet-tensorflow@noreply.github.com>; 
抄送: "雎园绿竹"<1063684795@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [IDKiro/CBDNet-tensorflow] batchsize (#5)




看你的描述，你的memory error指的是显存不够，那你修改 PS = 512 便可以，这是patch_size的大小（指裁剪的输入图像的大小），batch_size是1。

**Comment by IDKiro** [comment]
没有这个参数，写的时候为了节约读取图片的时间，把所有图片保留在内存里。
因为真实噪声的图片数据集单张图片很大，读取时间要比跑一次还要长几倍。
你如果想自己训练，那你可以把real数据集中的部分文件移出进行训练。

如果你想要训练好的模型，我正好机子空下来了可以重新训练，明天应该就可以上传所有预训练模型供测试修改。

**Comment by haoyuee** [comment]
好的，谢谢您将要提供的预训练模型，这对我帮助很大！




------------------ 原始邮件 ------------------
发件人: "IDKiro"<notifications@github.com>; 
发送时间: 2019年7月11日(星期四) 上午10:58
收件人: "IDKiro/CBDNet-tensorflow"<CBDNet-tensorflow@noreply.github.com>; 
抄送: "雎园绿竹"<1063684795@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [IDKiro/CBDNet-tensorflow] batchsize (#5)




没有这个参数，写的时候为了节约读取图片的时间，把所有图片保留在内存里。
 因为真实噪声的图片数据集单张图片很大，读取时间要比跑一次还要长几倍。
 你如果想自己训练，那你可以把real数据集中的部分文件移出进行训练。
 
如果你想要训练好的模型，我正好机子空下来了可以重新训练，明天应该就可以上传所有预训练模型供测试修改。

**Comment by IDKiro** [comment]
模型已上传，另外在训练过程中发现了一个上次修改模型后产生的bug，所以代码也作了修改，请自行更新。
