### ISSUE TITLE
Some questions after reviewing your codes

### ISSUE THREAD

**Issue by eastchun** [IDKiro/CBDNet-tensorflow#6]
Thanks for your efforts and fancy codes. 
You did great job and it is very helpful.

After I reviewed your codes, I came up with the following questions. 
I would appreciate if you kindly give me your feedback on these inquiries.

1) Where did you get your training and test images (those in your dataset folder in One Drive/Baidu, etc.)?  I mean the names of these dataset?

  - GT images in synthetic folder.
  - GT (Reference) - noisy images for real folder.
  - Test images.

     The above don't appear to be DND, Nam or NC12 dataset used in CBDNet matlab?

2) Where can I find the corresponding GT images for your noisy test images?

3) Regarding your trained model in checkpoint ...

Is this a training result that exactly followed your training parameters and environment in your code? (i.e., 200 epochs for 3000 synthetics images + 120 real images with REPEAT=10, for dataset in synthetic and real ? )

Could you say that this trained model is comparable with the trained model in CBDNet Matlab (original CBDNet repository) in terms of real-noise denoising capability?

4) Do you have a plan to include CBDNet-JPEG?   

Thanks in advance.

East

**Comment by IDKiro** [comment]
Train:
synthetic: MIT-Adobe FiveK
real: RENOIR
Test:
converted DND (.mat to .bmp, for better observing)
If you want to submit the results to DND website, please use the official kit.

Because it is a simple implementation, it does not use all the datasets mentioned in the papers, but the datasets used are all mentioned in the paper.

**Comment by IDKiro** [comment]
Q2: The DND doesn't provide gt images. You can only submit your results to website.

**Comment by IDKiro** [comment]
Q3: Sorry, I can't guarantee it. This project is for study only.

**Comment by IDKiro** [comment]
Q4: same as Q3.

**Comment by eastchun** [comment]
Thanks.
How about the following question ?

** Regarding your trained model in the checkpoint ...

Is this a training result that exactly followed your training parameters and environment in your code? i.e., 200 epochs for 3000 synthetics images + 120 real images with REPEAT=10, for dataset in synthetic and real ?

**Comment by IDKiro** [comment]
I'm sorry, but not.

**Comment by eastchun** [comment]
Then, how did you come up with the above training parameters (i.e., 200 epochs, REPEAT=10) ?

**Comment by IDKiro** [comment]
Just to make the iteration times of synthesis dataset and real dataset within each epoch subtantially equal.

**Comment by eastchun** [comment]
Then, 

How about 200 epochs? 

Also, how many epochs did you run to get the trained model in the checkpoint?

**Comment by IDKiro** [comment]
emmmm, surely 200 epochs. Based on experience?

I can't answer too many trivial questions. Issue is not for replying this kind of questions.

Some problems are no longer a problem when you have experience.

GL.
