### ISSUE TITLE
Model architecture problem

### ISSUE THREAD

**Issue by WXR1998** [IDKiro/CBDNet-tensorflow#7]
In the model.py, there is a problem in the architecture of the network:
tensors _conv4_ and _conv5_ are not properly set. Please fix this.

**Comment by IDKiro** [comment]
What's the problem?

**Comment by WXR1998** [comment]
up4 = upsample_and_sum(conv3, conv2, 128, 256, scope='deconv4')
        conv4 = slim.conv2d(up4, 128, [3, 3], rate=1, activation_fn=tf.nn.relu, scope='conv4_1')
        conv4 = slim.conv2d(**up4**, 128, [3, 3], rate=1, activation_fn=tf.nn.relu, scope='conv4_2')
        conv4 = slim.conv2d(**up4**, 128, [3, 3], rate=1, activation_fn=tf.nn.relu, scope='conv4_3')

        up5 = upsample_and_sum(conv4, conv1, 64, 128, scope='deconv5')
        conv5 = slim.conv2d(up5, 64, [3, 3], rate=1, activation_fn=tf.nn.relu, scope='conv5_1')
        conv5 = slim.conv2d(**up5**, 64, [3, 3], rate=1, activation_fn=tf.nn.relu, scope='conv5_2')

**Comment by IDKiro** [comment]
OK, i have fixed it, thanks very much.
